import type { Metadata } from "next";
import { Roboto, Barlow, Ysabeau_SC } from "next/font/google";
import "./globals.css";
import Footer from "@/(components)/Footer";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ["100", "300", "500", "700"]
})
const barlow = Barlow({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-barlow',
  weight: ["100", "200", "300", "500", "700"]
})

const ysabeau = Ysabeau_SC({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ysabeau',
  weight: ["100", "200", "300", "500", "700"]
})

export const metadata: Metadata = {
  title: "Math Modeling",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (  
    <html lang="en" className={`${barlow.variable} ${ysabeau.variable} ${roboto.variable}`}>
      <body className="app">
        
        <main>
        {children}
        </main>
        <Footer/>        
        </body>
    </html>
  );
}

